# These values will be overridden by the deployer container during installation
image:
  # In production, this matches your Artifact Registry path: gcr.io/my-project/my-app
  repository: us-docker.pkg.dev/searce-cloud-products/mp-poc-k8s-denis/my-poc-app
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80
