apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "searce-cloud-products", "product_id": "ibm-poc-app-k8s", "partner_name": "Human Friendly Name"}'
spec:
  descriptor:
    type: "gcp-marketplace-poc"
    version: "1.0.0"
    description: "My GCP Marketplace Proof of Concept Application."
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
