apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-license-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
type: Opaque
data:
  # Base64 encode the license key from the schema user input
  license-key: {{ .Values.licenseKey | b64enc | quote }}