# apptest/deployer/schema.yaml
x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: "Automated test release"
    releaseTypes:
    - Feature
    recommended: false
  images:
    "":
      properties:
        repository:
          type: FULL
          default: us-docker.pkg.dev/searce-cloud-products/gcp-mp-poc-k8s/app:1.0.0

properties:
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  name:
    type: string
    x-google-marketplace:
      type: NAME

  # ── INJECTED TEST DEFAULTS ────────────────────────────────────────────────
  license.licenseKey:
    type: string
    default: "8678bf7d596df3a020ed51f1fa1129ecde2497773b14426b565140d71debfd20"
  
  license.licenseSecret:
    type: string
    default: "marketplace-test-secret"

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
    default: "test-reporting-secret"

required:
  - name
  - namespace
  - license.licenseKey
  - license.licenseSecret
  - reportingSecret