x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: "Initial release."
    releaseTypes:
    - Feature
    recommended: false
  images:
    appImage:
      properties:
        repository:
          type: FULL
          default: us-docker.pkg.dev/searce-cloud-products/gcp-mp-poc-k8s/app:1.0.0

properties:
  namespace:
    type: string
    title: Namespace
    description: The Kubernetes namespace where the app will be deployed.
    x-google-marketplace:
      type: NAMESPACE

  name:
    type: string
    title: Application Name
    description: The name of this application instance.
    x-google-marketplace:
      type: NAME

  licenseKey:
    type: string
    title: BYOL License Key
    description: Your pre-purchased license key. Contact support to obtain a license.

  licenseSecret:
    type: string
    title: License Validation Secret
    description: The HMAC secret used to verify the license key.

  reportingSecret:
    type: string
    title: Reporting Secret
    description: A secret generated by Google to track usage.
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - licenseKey
  - licenseSecret
  - reportingSecret